spring.application.name=api

spring.datasource.url=jdbc:mysql://localhost/ebanx_api
spring.datasource.username=root
spring.datasource.password=root@MySQL

# para criar a(s) tabela(s)
spring.jpa.hibernate.ddl-auto=update

# força o Spring a sempre processar scripts de inicialização de dados
spring.sql.init.mode=always

# garante que o data.sql só rode após que o Hibernate gerar as tabelas
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true